# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Edward Duro | Web Dev Blog
email: e.jamesduro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Follow me on my journey through the vast information of Front End and Back End web developement. 
 Front end web developer living in Portland, OR.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eddieduro.github.io/" # the base hostname & protocol for your site
twitter_username: e_jamesduro
github_username:  eddieduro

# Build settings
markdown: kramdown
